import { div } from 'motion/react-client'
import React from 'react'

const Project = () => {
  return (
    <div id="project" className='w-full h-auto'>
    <div className="bg-[url('/bg1.png')] bg-cover bg-center w-full h-full ">
      <p>
        Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eveniet ea iure temporibus sapiente laboriosam, officiis nemo maxime. Eaque nobis neque itaque aliquid error exercitationem fugit odit placeat culpa nesciunt nisi excepturi sapiente atque, eligendi totam maxime, porro sequi recusandae corrupti minima, incidunt ipsum veritatis. Neque non pariatur vel nostrum consectetur maiores nobis quod commodi porro maxime iure harum, nam fuga velit, fugit numquam quaerat corporis. Cumque architecto illum ipsum hic minima voluptatibus laborum voluptas maiores dolores, eligendi accusamus sit, saepe, dolore at expedita. Facilis laudantium, dolorem similique, non provident sit, blanditiis ad iusto necessitatibus in quidem! Tempora ut iusto reiciendis dolor illum nisi autem, molestias dignissimos ipsa itaque vero voluptatem expedita a non maiores? Ea debitis et nihil dicta sed numquam rem eum natus asperiores sunt? Fugiat, quibusdam odit quasi quas doloremque sapiente, nihil accusantium officia magni reiciendis harum eum. Velit quae, officiis animi nam dolore debitis tempora cum doloremque officia qui repellat consequuntur sed neque inventore fugit aut quas, voluptatum adipisci ipsum. Voluptates aliquam quia odit ipsa necessitatibus iste esse voluptas, odio labore quae dolores dolor unde laborum possimus repellat, enim blanditiis quis vitae illo minima itaque qui reprehenderit. Veritatis excepturi dolorum, magni, commodi earum alias, ad quibusdam facere rem et quas totam eius vitae non sequi est labore quasi! Cupiditate nihil maiores possimus explicabo reprehenderit. Vitae vero repellat cumque odit commodi minus magni recusandae possimus id beatae quod quisquam quis iusto, pariatur placeat tempore veritatis consequuntur eaque culpa velit dicta sint fugiat iure temporibus. Temporibus rem dignissimos, quia sint ab recusandae perferendis fuga commodi et. Pariatur labore repellendus exercitationem blanditiis rerum placeat temporibus nostrum quos! Reiciendis dolore, minima deleniti facilis illo exercitationem maiores laborum nobis illum eius assumenda incidunt cupiditate veritatis perferendis nihil aspernatur accusantium alias consequatur adipisci dolorum qui temporibus laboriosam. Labore quisquam adipisci aliquid minus. Ducimus.
        Lorem ipsum, dolor sit amet consectetur adipisicing elit. Iure laborum impedit assumenda repellendus cum consequuntur accusamus commodi, repudiandae aliquam soluta qui temporibus sed? Quam, enim quia. Qui eveniet explicabo repudiandae aspernatur, quod natus corrupti velit minima ad! Id, voluptates. Hic, dolorem. Praesentium neque, temporibus quo tenetur nisi amet quidem recusandae quae ipsam cumque aliquid aliquam consequuntur, minus dolore officiis in magnam rerum est adipisci totam ex enim quaerat? Voluptatibus aspernatur illum reprehenderit modi voluptates. Voluptate cum nemo quas! Saepe enim, ullam neque atque dolore ex sapiente tempora qui! Eaque id deleniti labore, voluptates dolore illo rerum quos voluptatibus aliquid possimus! Quod possimus cupiditate nam! Cumque nostrum vel minus laboriosam voluptates ratione soluta illo! Architecto consequatur quisquam distinctio ea eos quae illum earum magnam vero. Distinctio reiciendis natus cum illum aut, totam, earum necessitatibus ipsum provident fugiat ex doloremque porro consequuntur nostrum harum ullam. Iure ex minima corrupti commodi neque molestiae, repellat rem nesciunt temporibus velit deserunt adipisci, voluptatem facere quisquam est assumenda! Fugit impedit voluptatum in, adipisci expedita accusantium sapiente similique necessitatibus, porro ipsam dolorem hic minus. Cumque, deleniti! Qui omnis temporibus assumenda eius eveniet explicabo unde amet veniam adipisci quibusdam expedita pariatur dolore dignissimos animi doloribus nostrum ad iusto a, maiores accusantium ut autem quisquam asperiores officia! Hic cupiditate ad distinctio quisquam laborum cumque provident assumenda sit pariatur quo molestias non commodi voluptas veniam quaerat ex, sapiente expedita repudiandae eius minima reprehenderit sequi voluptatem iste dignissimos? Eaque dolor sunt ex impedit, facilis quo dolorum illum in natus quod eveniet voluptatum tempora quia suscipit labore aut tenetur. Natus, accusantium! Sed nesciunt non, cum porro itaque molestias tenetur adipisci quia eligendi officia excepturi corrupti laboriosam possimus, labore obcaecati? Consectetur, aperiam. Vel illum nesciunt dicta maxime perferendis velit architecto culpa. Voluptatibus unde velit animi recusandae, veniam facilis impedit debitis sapiente eum facere.
        Lorem ipsum dolor sit, amet consectetur adipisicing elit. Esse dignissimos temporibus debitis? Laboriosam consequuntur quae autem quaerat nostrum magni id vero, iste nemo rem eum molestiae ex assumenda velit non eius, eveniet delectus fuga? Ipsa commodi dolorum quia excepturi, neque illum debitis ipsum accusantium maxime earum aut rem a sed blanditiis assumenda dolorem, aperiam magni iste amet quibusdam. Sit iusto quasi eveniet quis commodi possimus dolor aliquam! Culpa, eveniet eum rerum soluta fugiat delectus voluptatum earum enim laboriosam illum quidem quia! Non culpa itaque doloribus tenetur deserunt a rerum magnam voluptatum exercitationem quasi eius vel similique, adipisci, earum, sunt mollitia.
      </p>
    </div>
    </div>
  )
}

export default Project
